### ISSUE TITLE
BiggerStreamPreview breaking all interactions

### ISSUE THREAD

**Issue by GenesisAria** [jaimeadf/BetterDiscordPlugins#237]
In some servers, having BSP in causes discord to stop responding to inputs in the ui after right-clicking someone.  Cannot close popup or navigate anywhere until relaoding.

**Comment by ScottsplaysSus** [comment]
Same issue here. It also crashes Discord if I try to right-click on someone avatar in a server. The photos attached are the crash and the Console tab(you can use ctrl + shift + i to open the tab) for Discord after the crash. Note that in the second picture, the reason that the special debug info appeared on the Console is because I have another plugin installed, the name of the plugin is CrashRecovery (this plugin is useful, I recommend installing it). It can help debug the cause of the crash, and also you don't need to reload Discord most of the time after it crashed.   I tried disabling the plugin and everything went back to normal, but once I enabled the plugin, it crashes again. Please release a fix. Thanks. 

Sorry for the bad English, I hope you understand what I'm saying :D

![image](https://user-images.githubusercontent.com/91255736/150119529-dc221892-7e85-4b24-80eb-15e99837319c.png)

![image](https://user-images.githubusercontent.com/91255736/150119965-13fcb5f2-31f6-47a9-824a-5e02b6cd4178.png)

**Comment by GenesisAria** [comment]
Mine doesn't crash, it just opens the popup and then i can't click anywhere or close the popup or check a dm or type, i have to reload to be able to do anything.

**Comment by ScottsplaysSus** [comment]
I have the same problem with you too! Unfortunately for me, it also crashes lol. I already disabled the plugin and everything works fine now. Hope the devs can fix this issue :D

**Comment by jaimeadf** [comment]
I couldn't find a way to replicate this issue, but I made some changes. Please, let me know if I have fixed it or not.

**Comment by ScottsplaysSus** [comment]
Alright, thanks for the update. I'll check it out later and see whether it still crashes Discord or not. Thanks :D

**Comment by jaimeadf** [comment]
Glad it worked.
